<?xml version="1.0"?>
<package format="2">
  <name>rgbd_sim</name>
  <version>0.0.1</version>
  <description>Simulacion ROS1 + Gazebo de camara RGB-D y objetivo humanoide movil.</description>

  <maintainer email="you@example.com">you</maintainer>
  <license>MIT</license>

  <buildtool_depend>catkin</buildtool_depend>

  <depend>rospy</depend>
  <depend>roscpp</depend>
  <depend>std_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>gazebo_msgs</depend>
  <depend>gazebo_ros</depend>
  <exec_depend>rviz</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
</package>
